### ISSUE TITLE
Potential null pointer error?

### ISSUE THREAD

**Issue by Cryomundus** [FDAapproved/altis-over-and-under-shotgun#1]
Haven't encountered this myself, but according to HasenTZ the Altis can randomly crash. Took the screenshot they provided and uploaded it here.
![Screenshot_20231123_231944](https://github.com/FDAapproved/altis-over-and-under-shotgun/assets/70421214/44152850-3793-4381-b7ac-2a17ceca2ad4)

**Comment by FDAapproved** [comment]
Fixed with the latest push, so I'll be closing this. Release 1.6's patch notes will include a link back to this issue, also.
